spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
  jpa:
    show-sql: true
#将该商品服务注册到eureka上面
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



